In [58]:
import math

In [69]:
print(math.degrees(3.14159265)) #конвертация из радианов в градусы и обратно
print(math.radians(180))

179.99999979432002
3.141592653589793


In [ ]:
import numpy as np

In [47]:
O = np.zeros((3,3)) #массив 0
print(O.dtype)
print(O.shape)
print(O.size)

float64
(3, 3)
9


In [248]:
K = np.ones((2,2,3,3)) #4 мерный массив
print("K "*20)
print(K)
print("Shape: ", K.shape)
print("Dimensions: ", K.ndim)

K K K K K K K K K K K K K K K K K K K K 
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
Shape:  (2, 2, 3, 3)
Dimensions:  4


In [240]:
print("k "*20)
arr = np.arange(1,37,1)
k = arr.reshape((2,2,3,3))
print(k)

k k k k k k k k k k k k k k k k k k k k 
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]

  [[28 29 30]
   [31 32 33]
   [34 35 36]]]]


In [166]:
New_K = K+k
print("K+k "*10)
print(New_K)

K+k K+k K+k K+k K+k K+k K+k K+k K+k K+k 
[[[[ 2.  3.  4.]
   [ 5.  6.  7.]
   [ 8.  9. 10.]]

  [[11. 12. 13.]
   [14. 15. 16.]
   [17. 18. 19.]]]


 [[[20. 21. 22.]
   [23. 24. 25.]
   [26. 27. 28.]]

  [[29. 30. 31.]
   [32. 33. 34.]
   [35. 36. 37.]]]]


In [183]:
New_K2 = (K+K)*k
print("(K+K)*k "*10)
print(New_K2)
print(New_K2[1,1,2,2]) # должно быть значение 72 ((1+1)*36)
print(New_K2[1,0,0,0]) # должно быть значение 38 ((1+1)*19)

(K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k (K+K)*k 
[[[[ 2.  4.  6.]
   [ 8. 10. 12.]
   [14. 16. 18.]]

  [[20. 22. 24.]
   [26. 28. 30.]
   [32. 34. 36.]]]


 [[[38. 40. 42.]
   [44. 46. 48.]
   [50. 52. 54.]]

  [[56. 58. 60.]
   [62. 64. 66.]
   [68. 70. 72.]]]]
72.0
38.0


In [218]:
z1,z2 = np.hsplit(New_K, 2)
z11,z12 = np.vsplit(z1, 2)
print(z11)
print("-"*20)
print(z12)
print("-"*30)
z21,z22 = np.vsplit(z2, 2)
print(z21)
print("-"*20)
print(z22)

[[[[ 2.  3.  4.]
   [ 5.  6.  7.]
   [ 8.  9. 10.]]]]
--------------------
[[[[20. 21. 22.]
   [23. 24. 25.]
   [26. 27. 28.]]]]
------------------------------
[[[[11. 12. 13.]
   [14. 15. 16.]
   [17. 18. 19.]]]]
--------------------
[[[[29. 30. 31.]
   [32. 33. 34.]
   [35. 36. 37.]]]]


In [233]:
Z = np.copy(z12)
Z = Z+z22 # проверим что это копия z12, а не ссылка
print(Z)
print("Массивы отличаются")
print(z12) 

[[[[49. 51. 53.]
   [55. 57. 59.]
   [61. 63. 65.]]]]
Массивы отличаются
[[[[20. 21. 22.]
   [23. 24. 25.]
   [26. 27. 28.]]]]


In [251]:
import numpy as np
import numpy.random as rand

In [275]:
Rand = np.random.randint(-8,8,(2,2,3,3))
Rand

array([[[[ 3, -6,  6],
         [ 4,  1,  4],
         [-2, -6,  6]],

        [[-5,  7,  4],
         [ 2,  7, -4],
         [ 6, -4,  2]]],


       [[[-1,  7, -6],
         [ 0,  2, -7],
         [ 0, -4, -6]],

        [[ 7, -1,  5],
         [-4,  6,  1],
         [ 3,  3,  2]]]])

In [288]:
(Z+Rand)/np.max(Z+Rand) #Массив Z со случайным изменением, приведенный к нормализированному виду

array([[[[0.73239437, 0.63380282, 0.83098592],
         [0.83098592, 0.81690141, 0.88732394],
         [0.83098592, 0.8028169 , 1.        ]],

        [[0.61971831, 0.81690141, 0.8028169 ],
         [0.8028169 , 0.90140845, 0.77464789],
         [0.94366197, 0.83098592, 0.94366197]]],


       [[[0.67605634, 0.81690141, 0.66197183],
         [0.77464789, 0.83098592, 0.73239437],
         [0.85915493, 0.83098592, 0.83098592]],

        [[0.78873239, 0.70422535, 0.81690141],
         [0.71830986, 0.88732394, 0.84507042],
         [0.90140845, 0.92957746, 0.94366197]]]])